spring:
  config:
    import: optional:file:.env[.properties]

  application:
    name: bookhub

  threads:
    virtual:
      enabled: true

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true

  h2:
    console:
      enabled: true

logging:
  pattern:
    console: '[%d{HH:mm:ss.SSS}][%-5level][%logger.%method:line%line] - %msg%n'
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace